#!/usr/bin/env python3
"""Emit the browser playground's conversion data from the installed viparse.

The playground converts pasted text, which needs the charmaps, the glyph substitutions
and the frequency model — not the extraction engines, which are most of the library and
irrelevant without a file. So it runs a TypeScript port rather than a 10 MB Pyodide
download that would boot for seconds before a visitor could type anything.

A port can drift from what it ports. That is what this script is for: the data is read
out of the installed package and written verbatim, so the two cannot disagree about a
mapping. `npm run check:tables` re-runs it and fails if the checked-in file is stale.

    python3 scripts/generate-tables.py > src/lib/viparse-tables.generated.ts
"""

from __future__ import annotations

import json
import sys

from viparse import __version__
from viparse.normalize.detector import (
    _ALIEN_LETTERS,
    _ALIEN_RATE_CEILING,
    _CONTENT_MARGIN,
    _CONTENT_SEPARATION,
    _LONG_WORD_LETTERS,
    _LONG_WORD_RATE_CEILING,
)
from viparse.normalize.encodings import AUTO_DETECT_CHARMAPS, CHARMAPS
from viparse.normalize.frequency import _model
from viparse.normalize.tables import _GLYPH_SUBSTITUTIONS


def main() -> int:
    logp, floor = _model()
    payload = {
        "viparseVersion": __version__,
        "charmaps": {name: list(cm.pairs) for name, cm in CHARMAPS.items()},
        "autoDetect": sorted(AUTO_DETECT_CHARMAPS),
        "glyphSubstitutions": _GLYPH_SUBSTITUTIONS,
        "frequency": {"logp": logp, "floor": floor},
        "thresholds": {
            "contentMargin": _CONTENT_MARGIN,
            "contentSeparation": _CONTENT_SEPARATION,
            "alienLetters": "".join(sorted(_ALIEN_LETTERS)),
            "alienRateCeiling": _ALIEN_RATE_CEILING,
            "longWordLetters": _LONG_WORD_LETTERS,
            "longWordRateCeiling": _LONG_WORD_RATE_CEILING,
        },
    }
    print("// Generated by scripts/generate-tables.py — do not edit.")
    print("// Read verbatim out of the installed viparse so the playground and the")
    print("// library cannot disagree about a mapping. Re-run: npm run gen:tables")
    print()
    print("export const VIPARSE_DATA = " + json.dumps(payload, ensure_ascii=False, indent=2) + " as const")
    return 0


if __name__ == "__main__":
    sys.exit(main())
